/**
 * Registry of Open Community Challenge API
 * The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChallengePlatformAllOf } from './challengePlatformAllOf';
import { ChallengePlatformCreateResponse } from './challengePlatformCreateResponse';
import { ChallengePlatformCreateRequest } from './challengePlatformCreateRequest';


/**
 * A challenge platform
 */
export interface ChallengePlatform { 
    /**
     * The ID of the challenge platform
     */
    id: string;
    /**
     * The name of the challenge platform
     */
    name: string;
    /**
     * The URL to the homepage of the challenge platform
     */
    url: string;
    /**
     * When this challenge platform has been created
     */
    createdAt: string;
    /**
     * When this challenge platform has last been updated
     */
    updatedAt: string;
}

