/**
 * Registry of Open Community Challenges API
 * The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The role of a challenge sponsor
 */
export type ChallengeSponsorRole = 'ChallengeOrganizer' | 'CloudProvider' | 'DataProvider' | 'Funder' | 'Other';

export const ChallengeSponsorRole = {
    ChallengeOrganizer: 'ChallengeOrganizer' as ChallengeSponsorRole,
    CloudProvider: 'CloudProvider' as ChallengeSponsorRole,
    DataProvider: 'DataProvider' as ChallengeSponsorRole,
    Funder: 'Funder' as ChallengeSponsorRole,
    Other: 'Other' as ChallengeSponsorRole
};

