/**
 * Registry of Open Community Challenge API
 * The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonCreateResponse } from './personCreateResponse';
import { PersonCreateRequest } from './personCreateRequest';


/**
 * A person
 */
export interface Person { 
    /**
     * The unique identifier of a person
     */
    id: string;
    name: string;
    /**
     * An email address
     */
    email?: string;
    organizationIds: Array<string>;
}

