/**
 * Registry of Open Community Challenge API
 * The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserCreateResponse } from './userCreateResponse';
import { UserAllOf } from './userAllOf';
import { UserCreateRequest } from './userCreateRequest';


/**
 * A simple user
 */
export interface User { 
    /**
     * The unique identifier of an account
     */
    id: string;
    login: string;
    /**
     * An email address
     */
    email: string;
    name?: string | null;
    avatarUrl?: string | null;
    createdAt: string;
    updatedAt: string;
    type: string;
}

