/**
 * Registry of Open Community Challenge API
 * The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
 *
 * The version of the OpenAPI document: 0.1.4
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChallengeCreateRequest } from './challengeCreateRequest';
import { ChallengeCreateResponse } from './challengeCreateResponse';
import { ChallengeResults } from './challengeResults';
import { ChallengeStatus } from './challengeStatus';


/**
 * A challenge
 */
export interface Challenge { 
    /**
     * The ID of the challenge
     */
    challengeId?: string;
    /**
     * The challenge name
     */
    name: string;
    /**
     * When the challenge started
     */
    startDate: string;
    /**
     * When the challenge ended
     */
    endDate: string;
    /**
     * The URL to the challenge website
     */
    url?: string;
    status: ChallengeStatus;
    /**
     * The tags associated to the challenge
     */
    tags?: Array<string>;
    challengeResults?: ChallengeResults;
    /**
     * The organizers of the challenge
     */
    organizers?: Array<string>;
}

