/**
 * Registry of Open Community Challenge API
 * The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
 *
 * The version of the OpenAPI document: 0.1.4
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The results of a challenge
 */
export interface ChallengeResults { 
    /**
     * Number of total submissions throughout the challenge
     */
    nSubmissions?: number;
    /**
     * Number of final submissions
     */
    nFinalSubmissions?: number;
    /**
     * Number of registered participants
     */
    nRegisteredParticipants?: number;
}

